# These are supported funding model platforms

# GitHub Sponsors (if you have one set up)
# github: yourusername

# Custom donation links
custom:
  - https://etherscan.io/address/REDACTED_WALLET_ADDRESS

# Ethereum address for direct donations
# ETH/ERC-20/Polygon/Base/Arbitrum: REDACTED_WALLET_ADDRESS
