# These are supported funding model platforms

# GitHub Sponsors
github: flaukowski

# Custom donation links
# Set DONATION_ETH_ADDRESS in your environment to enable direct ETH donations
# custom:
#   - https://etherscan.io/address/<your-eth-address>
